// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqzruartxhljyxprhqkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxenJ1YXJ0eGhsanl4cHJocWtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDU1MzYsImV4cCI6MjA2NDM4MTUzNn0._V3_z2J35T4zRbRYsnQM29J6L5sWtECHNuaIU7h9-5E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);